<?php

namespace WebsiteBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastAdvert() {
    $qb = $this->createQueryBuilder('a');
    $qb->setMaxResults( 1 );
    $qb->orderBy('a.date_creation', 'DESC');

    return $qb->getQuery()->getSingleResult();
  }
}
