<?php

namespace WebsiteBundle\Repository;

/**
 * MediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MediaRepository extends \Doctrine\ORM\EntityRepository
{
  public function findLastMedia() {
    $qb = $this->createQueryBuilder('m');
    $qb->setMaxResults( 1 );
    $qb->orderBy('m.dateUpload', 'DESC');

    return $qb->getQuery()->getSingleResult();
  }
}
