<?php

namespace WebsiteBundle\Repository;

/**
 * ScPlaylistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScPlaylistRepository extends \Doctrine\ORM\EntityRepository
{
}
