website:
    resource: "@WebsiteBundle/Controller/"
    type:     annotation
    prefix:   /

login:
    path: /login
    defaults:
        _controller: UserBundle:Security:login

subscribe:
    path: /subscribe
    defaults:
        _controller: UserBundle:Security:subscribe

login_check:
    path: /login_check

logout:
    path: /logout
